render.yaml:
services:
  - type: web
    name: movies-flask-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade  # Apply migrations
    startCommand: gunicorn server.app:app